fixed syntax for terraform plan status

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -56,5 +56,4 @@ jobs:
       
       - name: Terraform Plan Status
         if: steps.plan.outcome == 'failure'
-        run: echo "Terraform plan failed. Please check the plan output for details."
-        run: exit 1
+        run: echo "Terraform plan failed. Please check the plan output for details." && exit 1
